name: PannelAppDB
channels:
  - defaults
dependencies:
  - pip == 23.3  
  - requests == 2.31.0
  - pandas == 2.1.1 
  - pytest == 7.4.0 
  - coverage == 7.2.2
  - responses == 0.13.3
  - tabulate == 0.9.0 

